export const PE_FIRMS = [
  { id: "mainsail", name: "Mainsail Partners", portfolioUrl: "https://www.mainsailpartners.com/portfolio/" },
  { id: "serent", name: "Serent Capital", portfolioUrl: "https://serentcapital.com/portfolio/" },
  { id: "jmi", name: "JMI Equity", portfolioUrl: "https://www.jmi.com/portfolio/" },
  { id: "insight", name: "Insight Partners", portfolioUrl: "https://www.insightpartners.com/portfolio/" },
  { id: "sumeru", name: "Sumeru Equity", portfolioUrl: "https://www.sumeruequity.com/portfolio/" },
  { id: "marlin", name: "Marlin Equity Partners", portfolioUrl: "https://www.marlinequity.com/portfolio/" },
  { id: "thoma", name: "Thoma Bravo", portfolioUrl: "https://www.thomabravo.com/portfolio" },
  { id: "vista", name: "Vista Equity Partners", portfolioUrl: "https://www.vistaequitypartners.com/portfolio.html" },
  { id: "riverside", name: "The Riverside Company", portfolioUrl: "https://www.riversidecompany.com/portfolio/" },
  { id: "frontenac", name: "Frontenac Company", portfolioUrl: "https://www.frontenac.com/portfolio/" },
  { id: "parkergale", name: "ParkerGale", portfolioUrl: "https://www.parkergale.com/portfolio" },
  { id: "resurgens", name: "Resurgens Technology Partners", portfolioUrl: "https://resurgenstech.com/portfolio/" },
  { id: "banneker", name: "Banneker Partners", portfolioUrl: "https://bannekerpartners.com/portfolio/" },
  { id: "silversmith", name: "Silversmith Capital Partners", portfolioUrl: "https://silversmith.com/portfolio/" },
  { id: "greater-sum", name: "Greater Sum Ventures", portfolioUrl: "https://greatersum.com/portfolio/" },
  { id: "bv", name: "BV Investment Partners", portfolioUrl: "https://www.bvlp.com/portfolio/" },
  { id: "susquehanna", name: "Susquehanna Growth Equity", portfolioUrl: "https://sgep.com/portfolio/" },
  { id: "level", name: "Level Equity", portfolioUrl: "https://www.levelequity.com/portfolio/" },
  { id: "tcv", name: "TCV", portfolioUrl: "https://www.tcv.com/companies/" },
  { id: "general-atlantic", name: "General Atlantic", portfolioUrl: "https://www.generalatlantic.com/portfolio" },
];
