export const PE_FIRMS = [
  { id: "mainsail", name: "Mainsail Partners", portfolioUrl: "https://www.mainsailpartners.com/portfolio/" },
  { id: "serent", name: "Serent Capital", portfolioUrl: "https://serentcapital.com/portfolio/" },
  { id: "parkergale", name: "ParkerGale", portfolioUrl: "https://www.parkergale.com/portfolio" },
  { id: "level", name: "Level Equity", portfolioUrl: "https://www.levelequity.com/portfolio/" },
  { id: "susquehanna", name: "Susquehanna Growth Equity", portfolioUrl: "https://sgep.com/portfolio/" },
  { id: "five-elms", name: "Five Elms Capital", portfolioUrl: "https://www.fiveelms.com/portfolio/" },
  { id: "silversmith", name: "Silversmith Capital Partners", portfolioUrl: "https://silversmith.com/portfolio/" },
  { id: "volition", name: "Volition Capital", portfolioUrl: "https://www.volitioncapital.com/portfolio" },
  { id: "resurgens", name: "Resurgens Technology Partners", portfolioUrl: "https://resurgenstech.com/portfolio/" },
  { id: "banneker", name: "Banneker Partners", portfolioUrl: "https://bannekerpartners.com/portfolio/" },
  { id: "jmi", name: "JMI Equity", portfolioUrl: "https://www.jmi.com/portfolio/" },
  { id: "georgian", name: "Georgian", portfolioUrl: "https://georgian.io/companies" },
  { id: "frontier", name: "Frontier Growth", portfolioUrl: "https://www.frontiergrowth.com/our-partnerships/" },
  { id: "peakspan", name: "PeakSpan Capital", portfolioUrl: "https://www.peakspancapital.com/" },
  { id: "accel-kkr", name: "Accel-KKR", portfolioUrl: "https://accel-kkr.com/platform-companies/all/" },
  { id: "summit", name: "Summit Partners", portfolioUrl: "https://summitpartners.com/portfolio/" },
  { id: "bertram-capital", name: "Bertram Capital", portfolioUrl: "https://www.bcap.com/companies/all" },
  { id: "bv", name: "BV Investment Partners", portfolioUrl: "https://www.bvlp.com/portfolio/" },
  { id: "greater-sum", name: "Greater Sum Ventures", portfolioUrl: "https://greatersum.com/portfolio/" },
  { id: "sp-investments", name: "Susquehanna Private Capital", portfolioUrl: "https://www.sqinvestco.com/companies/all" },
  { id: "marlin", name: "Marlin Equity Partners", portfolioUrl: "https://www.marlinequity.com/portfolio/" },
  { id: "riverside", name: "The Riverside Company", portfolioUrl: "https://www.riversidecompany.com/portfolio/" },
  { id: "frontenac", name: "Frontenac Company", portfolioUrl: "https://www.frontenac.com/portfolio/" },
  { id: "tcv", name: "TCV", portfolioUrl: "https://www.tcv.com/companies/" },
  { id: "insight", name: "Insight Partners", portfolioUrl: "https://www.insightpartners.com/portfolio/" },
  { id: "sumeru", name: "Sumeru Equity", portfolioUrl: "https://www.sumeruequity.com/portfolio/" },
  { id: "bregal-sagemount", name: "Bregal Sagemount", portfolioUrl: "https://www.sagemount.com/portfolio/" },
  { id: "ftv-capital", name: "FTV Capital", portfolioUrl: "https://www.ftvcapital.com/portfolio/" },
  { id: "general-atlantic", name: "General Atlantic", portfolioUrl: "https://www.generalatlantic.com/portfolio" },
  { id: "thoma", name: "Thoma Bravo", portfolioUrl: "https://www.thomabravo.com/portfolio" },
  { id: "clearlake", name: "Clearlake Capital", portfolioUrl: "https://www.clearlake.com/portfolio/" },
  { id: "welsh-carson", name: "Welsh, Carson, Anderson & Stowe", portfolioUrl: "https://www.welshcarson.com/portfolio/" },
  { id: "new-mountain", name: "New Mountain Capital", portfolioUrl: "https://www.newmountaincapital.com/portfolio/" },
  { id: "gtcr", name: "GTCR", portfolioUrl: "https://www.gtcr.com/portfolio/" },
  { id: "vista", name: "Vista Equity Partners", portfolioUrl: "https://www.vistaequitypartners.com/companies/" },
  { id: "hg", name: "Hg", portfolioUrl: "https://hgcapital.com/portfolio/" },
  { id: "ta-associates", name: "TA Associates", portfolioUrl: "https://www.ta.com/portfolio/" },
  { id: "battery", name: "Battery Ventures", portfolioUrl: "https://www.battery.com/company/" },
  { id: "psg", name: "PSG Equity", portfolioUrl: "https://www.psgequity.com/portfolio" },
  { id: "k1", name: "K1 Investment Management", portfolioUrl: "https://www.k1.com/portfolio/" },
  { id: "llr", name: "LLR Partners", portfolioUrl: "https://www.llrpartners.com/portfolio/" },
  { id: "spectrum", name: "Spectrum Equity", portfolioUrl: "https://www.spectrumequity.com/portfolio/" },
  { id: "strattam", name: "Strattam Capital", portfolioUrl: "https://www.strattam.com/portfolio" },
  { id: "lead-edge", name: "Lead Edge Capital", portfolioUrl: "https://leadedgecapital.com/portfolio/" },
  { id: "aquiline-tg", name: "Aquiline Technology Growth", portfolioUrl: "https://www.aquiline.com/portfolio/" },
  { id: "warburg", name: "Warburg Pincus", portfolioUrl: "https://www.warburgpincus.com/portfolio/" },
  { id: "francisco", name: "Francisco Partners", portfolioUrl: "https://www.franciscopartners.com/portfolio" },
  { id: "stg", name: "STG", portfolioUrl: "https://stg.com/portfolio/" },
  { id: "permira", name: "Permira", portfolioUrl: "https://www.permira.com/portfolio" },
  { id: "providence", name: "Providence Equity", portfolioUrl: "https://www.provequity.com/portfolio" },
  { id: "long-ridge", name: "Long Ridge Equity Partners", portfolioUrl: "https://www.long-ridge.com/portfolio/" },
  { id: "edison", name: "Edison Partners", portfolioUrl: "https://www.edisonpartners.com/portfolio" },
  { id: "arthur-ventures", name: "Arthur Ventures", portfolioUrl: "https://www.arthurventures.com/portfolio" },
  { id: "elsewhere", name: "Elsewhere Partners", portfolioUrl: "https://www.elsewhere.partners/portfolio" },

  // North America – additional growth equity & lower-middle market
  { id: "clovis-point", name: "Clovis Point Partners", portfolioUrl: "https://clovispoint.com/portfolio/" },
  { id: "aldrich", name: "Aldrich Capital Partners", portfolioUrl: "https://aldrichcapitalpartners.com/companies/" },
  { id: "cove-hill", name: "Cove Hill Partners", portfolioUrl: "https://www.covehillpartners.com/portfolio/" },
  { id: "sageview", name: "Sageview Capital", portfolioUrl: "https://www.sageviewcapital.com/portfolio/" },
  { id: "invictus", name: "Invictus Growth Partners", portfolioUrl: "https://www.invictusgrowth.com/companies" },
  { id: "vertica-cp", name: "Vertica Capital Partners", portfolioUrl: "https://verticacp.com/portfolio/" },
  { id: "harvest", name: "Harvest Partners", portfolioUrl: "https://harvestpartners.com/investments/" },
  { id: "accel", name: "Accel Partners", portfolioUrl: "https://www.accel.com/companies" },
  { id: "bvp", name: "Bessemer Venture Partners", portfolioUrl: "https://www.bvp.com/companies" },
  { id: "salesforce-ventures", name: "Salesforce Ventures", portfolioUrl: "https://salesforceventures.com/portfolio/" },
  { id: "crestview", name: "Crestview Partners", portfolioUrl: "https://www.crestviewpartners.com/portfolio/" },
  { id: "luminate", name: "Luminate Capital Partners", portfolioUrl: "https://www.luminatecapital.com/portfolio/" },
  { id: "columbia-lake", name: "Columbia Lake Partners", portfolioUrl: "https://www.columbialake.com/portfolio/" },
  { id: "blue-star", name: "Blue Star Innovation Partners", portfolioUrl: "https://www.bluestarinnovation.com/portfolio/" },
  { id: "golub-capital", name: "Golub Capital", portfolioUrl: "https://www.golubcapital.com/private-equity/portfolio/" },
  { id: "civc", name: "CIVC Partners", portfolioUrl: "https://www.civc.com/portfolio/" },
  { id: "riverwood", name: "Riverwood Capital", portfolioUrl: "https://www.riverwoodcapital.com/portfolio/" },
  { id: "guidepost", name: "Guidepost Growth Equity", portfolioUrl: "https://www.guidepostgrowth.com/portfolio/" },
  { id: "tritium", name: "Tritium Partners", portfolioUrl: "https://www.tritiumpartners.com/portfolio/" },
  { id: "fpe-capital", name: "FPE Capital", portfolioUrl: "https://www.fpecapital.com/portfolio" },
  { id: "acg-equity", name: "American Securities", portfolioUrl: "https://www.american-securities.com/portfolio/" },
  { id: "madison-dearborn", name: "Madison Dearborn Partners", portfolioUrl: "https://www.mdcp.com/portfolio/" },
  { id: "greenspring", name: "StepStone Group (Greenspring)", portfolioUrl: "https://www.stepstoneglobal.com/investments/" },
  { id: "norwest", name: "Norwest Venture Partners", portfolioUrl: "https://www.nvp.com/portfolio/" },
  { id: "iconiq", name: "ICONIQ Growth", portfolioUrl: "https://iconiqcapital.com/growth/portfolio/" },
  { id: "openview", name: "OpenView Venture Partners", portfolioUrl: "https://openviewpartners.com/portfolio/" },
  { id: "high-alpha", name: "High Alpha", portfolioUrl: "https://highalpha.com/portfolio/" },
  { id: "ridge-lane", name: "Ridge Lane Partners", portfolioUrl: "https://ridgelanepartners.com/portfolio/" },
  { id: "waud-capital", name: "Waud Capital Partners", portfolioUrl: "https://www.waudcapital.com/portfolio/" },
  { id: "abry", name: "ABRY Partners", portfolioUrl: "https://www.abry.com/portfolio/" },
  { id: "stone-point", name: "Stone Point Capital", portfolioUrl: "https://www.stonepoint.com/portfolio/" },

  // Europe – UK / Germany / France / Benelux
  { id: "fortino", name: "Fortino Capital", portfolioUrl: "https://www.fortino.group/companies/" },
  { id: "verto-growth", name: "Verto Growth", portfolioUrl: "https://vertogrowth.com/companies/" },
  { id: "oxx", name: "Oxx", portfolioUrl: "https://www.oxx.vc/portfolio/" },
  { id: "bregal-milestone", name: "Bregal Milestone", portfolioUrl: "https://www.bregalmilestone.com/portfolio/" },
  { id: "nordic-capital", name: "Nordic Capital", portfolioUrl: "https://www.nordiccapital.com/portfolio-cases/" },
  { id: "inflexion", name: "Inflexion", portfolioUrl: "https://www.inflexion.com/portfolio/" },
  { id: "ik-partners", name: "IK Partners", portfolioUrl: "https://www.ikpartners.com/investments/" },
  { id: "vitruvian", name: "Vitruvian Partners", portfolioUrl: "https://www.vitruvianpartners.com/portfolio/" },
  { id: "bowmark", name: "Bowmark Capital", portfolioUrl: "https://www.bowmark.com/investments" },
  { id: "apax", name: "Apax Partners", portfolioUrl: "https://www.apax.com/portfolio/" },
  { id: "waterland", name: "Waterland Private Equity", portfolioUrl: "https://www.waterlandpe.com/portfolio/" },
  { id: "oakley", name: "Oakley Capital", portfolioUrl: "https://www.oakleycapital.com/our-companies/" },
  { id: "bridgepoint", name: "Bridgepoint", portfolioUrl: "https://www.bridgepointgroup.com/portfolio/" },
  { id: "eqt", name: "EQT", portfolioUrl: "https://eqtgroup.com/current-portfolio/" },
  { id: "hig-europe", name: "H.I.G. Capital Europe", portfolioUrl: "https://higcapital.com/portfolio/" },
  { id: "cinven", name: "Cinven", portfolioUrl: "https://www.cinven.com/companies/" },
  { id: "cbpe", name: "CBPE Capital", portfolioUrl: "https://www.cbpecapital.com/portfolio/" },
  { id: "graphite", name: "Graphite Capital", portfolioUrl: "https://www.graphitecapital.com/portfolio/" },
  { id: "gresham", name: "Gresham Private Equity", portfolioUrl: "https://www.gpep.co.uk/portfolio/" },
  { id: "livingbridge", name: "Livingbridge", portfolioUrl: "https://www.livingbridge.com/portfolio/" },
  { id: "elvaston", name: "Elvaston Capital", portfolioUrl: "https://www.elvaston.com/portfolio/" },
  { id: "elazig", name: "Equistone Partners", portfolioUrl: "https://www.equistone.com/portfolio/" },
  { id: "hv-capital", name: "HV Capital", portfolioUrl: "https://www.hvcapital.com/portfolio/" },
  { id: "partech", name: "Partech", portfolioUrl: "https://partechpartners.com/companies/" },
  { id: "idinvest", name: "Eurazeo (idinvest)", portfolioUrl: "https://www.eurazeo.com/en/companies/" },
  { id: "holtzbrinck", name: "Holtzbrinck Ventures", portfolioUrl: "https://www.holtzbrinck-ventures.com/portfolio/" },
  { id: "nauta", name: "Nauta Capital", portfolioUrl: "https://nautacapital.com/portfolio/" },
  { id: "dawn", name: "Dawn Capital", portfolioUrl: "https://dawncapital.com/portfolio/" },
  { id: "espresso", name: "Espresso Capital", portfolioUrl: "https://www.espressocapital.com/portfolio/" },
  { id: "five-seasons", name: "Five Seasons Ventures", portfolioUrl: "https://fiveseasons.vc/portfolio/" },
  { id: "kibo", name: "Kibo Ventures", portfolioUrl: "https://kiboventures.com/portfolio/" },
  { id: "capza", name: "CAPZA", portfolioUrl: "https://www.capza.com/portfolio/" },
  { id: "sofina", name: "Sofina", portfolioUrl: "https://www.sofinagroup.com/our-portfolio/" },
  { id: "gimv", name: "Gimv", portfolioUrl: "https://www.gimv.com/portfolio/" },

  // Scandinavia / Nordics
  { id: "viking-growth", name: "Viking Growth", portfolioUrl: "https://vikinggrowth.com/companies" },
  { id: "monterro", name: "Monterro", portfolioUrl: "https://www.monterro.com/portfolio/" },
  { id: "vendep", name: "Vendep Capital", portfolioUrl: "https://www.vendep.com/portfolio" },
  { id: "gro-capital", name: "Gro Capital", portfolioUrl: "https://www.grocapital.dk/portfolio" },
  { id: "standout-cap", name: "Standout Capital", portfolioUrl: "https://standoutcapital.com/portfolio/" },
  { id: "verdane", name: "Verdane", portfolioUrl: "https://verdane.com/portfolio/" },
  { id: "norvestor", name: "Norvestor", portfolioUrl: "https://www.norvestor.com/investments" },
  { id: "summa-equity", name: "Summa Equity", portfolioUrl: "https://summaequity.com/portfolio/" },
  { id: "northzone", name: "Northzone", portfolioUrl: "https://northzone.com/portfolio/" },
  { id: "eir-ventures", name: "EQT Ventures", portfolioUrl: "https://eqtventures.com/portfolio/" },
  { id: "vaaka", name: "Vaaka Partners", portfolioUrl: "https://vaakapartners.fi/portfolio/" },
  { id: "bynd", name: "Bygge Software Holdco (BYND)", portfolioUrl: "https://www.bynd.io/portfolio/" },
  { id: "industrifonden", name: "Industrifonden", portfolioUrl: "https://www.industrifonden.com/portfolio/" },
  { id: "creades", name: "Creades", portfolioUrl: "https://www.creades.se/portfölj/" },
  { id: "alfvn-growth", name: "Alfvén & Didrikson", portfolioUrl: "https://www.alfven-didrikson.com/portfolio/" },
  { id: "scope", name: "Scope Capital", portfolioUrl: "https://www.scopecapital.se/portfolio/" },
  { id: "tesi", name: "Tesi (Finnish Industry Investment)", portfolioUrl: "https://www.tesi.fi/en/portfolio/" },
  { id: "sisu-capital", name: "Sisu Capital", portfolioUrl: "https://sisucapital.com/portfolio/" },
];
